import type { Metadata } from "next";
import {Geist, Geist_Mono, Roboto} from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import React from "react";
import LeftNav from "@/app/LeftNav";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} overflow-hidden`}>
        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          hideProgressBar={true}
          newestOnTop={true}
          closeOnClick={true}
        />
        <main className="grid size-full grid-cols-[auto_1fr] py-10 overflow-hidden divide-x divide-x-gray-300">
          <div className="py-6 flex min-w-40 flex-col items-center gap-6 border-y border-y-gray-300">
            <h1 className="text-xl underline"><Link href="/" className="hover:text-purple-200">SimpleRAG</Link></h1>
            <LeftNav/>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
